apiVersion: apps/v1
kind: Deployment
metadata:
 name: music
 namespace: vijaya
 labels:
  app: node
spec:
 replicas: 2
 selector:
  matchLabels:
   app: node
 template:
  metadata:
   name: music
   namespace: vijaya
   labels:
    app: node
  spec:
    containers:
    - name: music
      image: 922779268820.dkr.ecr.us-east-2.amazonaws.com/music:latest
      ports:
      - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
 name: music
 namespace: vijaya
spec:
 type: LoadBalancer
 ports:
 - port: 80
   targetPort: 3001
 selector:
   app: node
