apiVersion : apps/v1
kind: Deployment
metadata:
  name: magicregazurecrioapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magicregazurecrioapp
  template:
    metadata:
      labels:
        app: magicregazurecrioapp 
    spec:
      containers:
        - name: magicregazurecrioapp 
          image: magicreg.azurecr.io/magicregazurecrioapp
          ports:
          - containerPort: 3001